# Generated by Django 3.1.3 on 2020-12-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='template',
            field=models.TextField(blank=True),
        ),
    ]
