# Generated by Django 3.1.3 on 2020-12-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_app_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='template',
            field=models.CharField(max_length=150),
        ),
    ]
